# Generated by Django 4.2.16 on 2025-04-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceArea', '0002_area_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='price',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='language',
        ),
    ]
