# Generated by Django 4.2.16 on 2025-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceArea', '0003_remove_area_price_remove_provider_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
